import { Product } from "./domain/product";

export const products: Product[] = [
    {
        id: "1",
        name: "Smartphone Galaxy S21",
        description: "Smartphone Samsung com tela AMOLED de 6.2 polegadas.",
        quantityStock: 120,
        brand: "Samsung",
        discount: 10,
        quantitySold: 230,
        images: ["https://placehold.co/600x400/000000/FFF", "https://placehold.co/600x400/orange/white", "https://placehold.co/600x400/orange/white"],
        price: 3999.90,
    },
    {
        id: "2",
        name: "Notebook Dell XPS 13",
        description: "Ultrabook com processador Intel i7 e 16GB de RAM.",
        quantityStock: 45,
        brand: "Dell",
        discount: 0,
        quantitySold: 60,
        images: ["https://placehold.co/600x400/000000/FFF"],
        price: 7899.00,
    },
    {
        id: "3",
        name: "Fone Bluetooth JBL",
        description: "Fone de ouvido com cancelamento de ruído.",
        quantityStock: 300,
        brand: "JBL",
        discount: 5,
        quantitySold: 540,
        images: ["https://placehold.co/600x400/000000/FFF", "https://placehold.co/600x400/orange/white"],
        price: 349.90,
    },
    {
        id: "4",
        name: "Smart TV LG 55'",
        description: "Smart TV 4K com inteligência artificial.",
        quantityStock: 25,
        brand: "LG",
        discount: 20,
        quantitySold: 80,
        images: ["https://placehold.co/600x400/000000/FFF"],
        price: 2999.00,
    },
    {
        id: "5",
        name: "Câmera Canon EOS Rebel T7",
        description: "Câmera profissional com lente 18-55mm.",
        quantityStock: 70,
        brand: "Canon",
        discount: 0,
        quantitySold: 130,
        images: ["https://placehold.co/600x400/000000/FFF", "https://placehold.co/600x400/orange/white"],
        price: 2399.90,
    },
    {
        id: "6",
        name: "Console PlayStation 5",
        description: "Console de última geração da Sony.",
        quantityStock: 15,
        brand: "Sony",
        discount: 0,
        quantitySold: 400,
        images: ["https://placehold.co/600x400/000000/FFF"],
        price: 4599.99,
    },
    {
        id: "7",
        name: "Cadeira Gamer DXRacer",
        description: "Cadeira ergonômica para jogos.",
        quantityStock: 80,
        brand: "DXRacer",
        discount: 0,
        quantitySold: 220,
        images: ["https://placehold.co/600x400/000000/FFF"],
        price: 1399.00,
    },
    {
        id: "8",
        name: "Mouse Logitech MX Master 3",
        description: "Mouse ergonômico com alta precisão.",
        quantityStock: 210,
        brand: "Logitech",
        discount: 10,
        quantitySold: 340,
        images: ["https://placehold.co/600x400/000000/FFF"],
        price: 499.90,
    },
    {
        id: "9",
        name: "Teclado Mecânico Redragon",
        description: "Teclado RGB com switches blue.",
        quantityStock: 170,
        brand: "Redragon",
        discount: 25,
        quantitySold: 290,
        images: ["https://placehold.co/600x400/000000/FFF"],
        price: 299.90,
    },
    {
        id: "10",
        name: "Monitor LG Ultrawide 29''",
        description: "Monitor para produtividade e games.",
        quantityStock: 60,
        brand: "LG",
        discount: 8,
        quantitySold: 150,
        images: ["https://placehold.co/600x400/000000/FFF", "https://placehold.co/600x400/orange/white", "https://placehold.co/600x400/orange/white"],
        price: 1299.00,
    },
    {
        id: "11",
        name: "Roteador TP-Link Archer C6",
        description: "Roteador Wi-Fi Dual Band.",
        quantityStock: 95,
        brand: "TP-Link",
        discount: 20,
        quantitySold: 310,
        images: ["https://placehold.co/600x400/000000/FFF"],
        price: 199.90,
    },
    {
        id: "12",
        name: "Echo Dot 5ª Geração",
        description: "Alto-falante inteligente com Alexa.",
        quantityStock: 140,
        brand: "Amazon",
        discount: 0,
        quantitySold: 500,
        images: ["https://placehold.co/600x400/000000/FFF"],
        price: 349.00,
    },
    {
        id: "13",
        name: "HD Externo Seagate 2TB",
        description: "Armazenamento portátil USB 3.0.",
        quantityStock: 100,
        brand: "Seagate",
        discount: 17,
        quantitySold: 230,
        images: ["https://placehold.co/600x400/000000/FFF", "https://placehold.co/600x400/orange/white"],
        price: 429.90,
    },
    {
        id: "14",
        name: "SSD Kingston 480GB",
        description: "SSD com leitura rápida e confiável.",
        quantityStock: 130,
        brand: "Kingston",
        discount: 22,
        quantitySold: 370,
        images: ["https://placehold.co/600x400/000000/FFF", "https://placehold.co/600x400/orange/white"],
        price: 319.90,
    },
    {
        id: "15",
        name: "Impressora HP Ink Tank 416",
        description: "Impressora multifuncional tanque de tinta.",
        quantityStock: 35,
        brand: "HP",
        discount: 0,
        quantitySold: 90,
        images: ["https://placehold.co/600x400/000000/FFF"],
        price: 1149.00,
    },
    {
        id: "16",
        name: "Webcam Logitech C920",
        description: "Webcam Full HD com microfone embutido.",
        quantityStock: 85,
        brand: "Logitech",
        discount: 0,
        quantitySold: 270,
        images: ["https://placehold.co/600x400/000000/FFF","https://placehold.co/600x400/orange/white", "https://placehold.co/600x400/orange/white"],
        price: 449.90,
    },
    {
        id: "17",
        name: "Kindle Paperwhite 11ª Geração",
        description: "Leitor digital com luz embutida.",
        quantityStock: 55,
        brand: "Amazon",
        discount: 14,
        quantitySold: 195,
        images: ["https://placehold.co/600x400/000000/FFF"],
        price: 649.00,
    },
    {
        id: "18",
        name: "Aspirador Robô Xiaomi",
        description: "Aspirador inteligente com mapeamento.",
        quantityStock: 42,
        brand: "Xiaomi",
        discount: 18,
        quantitySold: 140,
        images: ["https://placehold.co/600x400/000000/FFF", "https://placehold.co/600x400/orange/white"],
        price: 1599.00,
    },
    {
        id: "19",
        name: "Relógio Smartwatch Amazfit",
        description: "Relógio inteligente com monitor de batimentos.",
        quantityStock: 110,
        brand: "Amazfit",
        discount: 9,
        quantitySold: 260,
        images: ["https://placehold.co/600x400/000000/FFF"],
        price: 499.00,
    },
    {
        id: "20",
        name: "Caixa de Som Bluetooth Anker",
        description: "Som potente e bateria de longa duração.",
        quantityStock: 200,
        brand: "Anker",
        discount: 0,
        quantitySold: 320,
        images: ["https://placehold.co/600x400/000000/FFF", "https://placehold.co/600x400/orange/white"],
        price: 369.00,
    },
];
